print("ML model start:")
options(warn =-1)
library(reshape2)
library(dplyr,warn.conflicts =F)
library(RMySQL)
library(stringr)
library(e1071)
#library(tcltk)
library(lubridate)
library(truncnorm)
library(cluster)
library(Rtsne)
library(tidyr)
library(mailR)
library(rlist)
library(RJSONIO)
#library(plyr)
price_model_loc<-gsub("(\\/main|\\/bat).*","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()}))
source(paste0(price_model_loc,"/function/yck_base_function.R"),echo=FALSE,encoding="utf-8")
source(paste0(price_model_loc,"/function/fun_model_price_test.R"),echo=FALSE,encoding="utf-8")
source(paste0(price_model_loc,"/function/yckit_project_user.R"),echo=FALSE,encoding="utf-8")
local_defin<-fun_mysql_config_up()
source(paste0(price_model_loc,"/function/f_model_interface.R"),echo=FALSE,encoding="utf-8")
source(paste0(price_model_loc,"/function/SerieStandardFun.R"),echo=FALSE,encoding="utf-8")
local_defin_yy<-data.frame(user = 'root',host='192.168.0.111',password= '000000',dbname='yck',stringsAsFactors = F)
#local_defin_yy<<-data.frame(user = 'data',host='www.youcku.com',password= '6wrzfhG',dbname='yck',stringsAsFactors = F)


##可售/不可售接口调用
local_defin_yun_it<<-data.frame(user = "data",host="120.79.98.108",password= "543asdfQ",dbname="yck",stringsAsFactors = F)
local_file<-paste0(price_model_loc,"/main_dctoit_prj")
source(paste0(local_file,"\\cfun_yck_itd_cars_salable.R"),echo=FALSE,encoding="utf-8")
