rm(list = ls(all=T))
gc()
library(dplyr)
library(RMySQL)
#price_model_loc<-gsub("\\/main","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()}))
local_defin<-data.frame(user = 'yckdc',host='47.106.189.86',password= 'YckDC888',dbname='yck-data-center',stringsAsFactors = F)
loc_channel<-dbConnect(MySQL(),user = local_defin$user,host=local_defin$host,password= local_defin$password,dbname=local_defin$dbname)
dbSendQuery(loc_channel,'SET NAMES gbk')
df_user_query_id<-dbFetch(dbSendQuery(loc_channel,'SELECT user_query_id FROM yck_project_model_query WHERE query_statue=3 OR DATEDIFF(NOW(),add_time)>6'),-1)
dbSendQuery(loc_channel,paste0('INSERT INTO yck_project_model_old_query SELECT * FROM yck_project_model_query WHERE user_query_id in(',paste0(df_user_query_id$user_query_id,collapse = ','),')'))
dbSendQuery(loc_channel,paste0('INSERT INTO yck_project_model_old_result_future SELECT * FROM yck_project_model_result_future WHERE user_query_id in(',paste0(df_user_query_id$user_query_id,collapse = ','),')'))
dbSendQuery(loc_channel,paste0('INSERT INTO yck_project_model_old_result_match SELECT * FROM yck_project_model_result_match WHERE user_query_id in(',paste0(df_user_query_id$user_query_id,collapse = ','),')'))
dbSendQuery(loc_channel,paste0('INSERT INTO yck_project_model_old_result_tag SELECT * FROM yck_project_model_result_tag WHERE user_query_id in(',paste0(df_user_query_id$user_query_id,collapse = ','),')'))
dbSendQuery(loc_channel,paste0('DELETE FROM yck_project_model_query WHERE user_query_id in(',paste0(df_user_query_id$user_query_id,collapse = ','),')'))
dbDisconnect(loc_channel)
