print("ML model start:")
options(warn =-1)
library(RODBC)
library(reshape2)
library(dplyr,warn.conflicts =F)
library(RMySQL)
library(stringr)
library(e1071)
#library(tcltk)
library(lubridate)
library(truncnorm)
library(cluster)
library(Rtsne)
library(tidyr)
price_model_loc<-gsub("\\/main|\\/bat","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()}))
source(paste0(price_model_loc,"\\function\\fun_mysql_config_up.R"),echo=FALSE,encoding="utf-8")
source(paste0(price_model_loc,"\\function\\fun_model_price_test.R"),echo=FALSE,encoding="utf-8")
local_defin<-fun_mysql_config_up()
source(paste0(price_model_loc,"\\function\\f_model_interface.R"),echo=FALSE,encoding="utf-8")