##对于系统车源（快进快出项目）报价处理过程
rm(list = ls(all=T))
gc()
library(reshape2)
library(dplyr)
library(RMySQL)
library(stringr)
library(tcltk)
library(lubridate)
library(truncnorm)
library(Rtsne)
library(rlist)
library(mailR)
options(scipen = 200)
price_model_loc<-gsub("(\\/main|\\/bat).*","",tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),error=function(e){getwd()}))
local_defin_yy<-data.frame(user = 'data',host='www.youcku.com',password= '6wrzfhG',dbname='yck',stringsAsFactors = F)
#local_defin_yy<-data.frame(user = 'root',host='192.168.0.111',password= '000000',dbname='yck',stringsAsFactors = F)
local_defin<-data.frame(user = 'root',host='192.168.0.111',password= '000000',dbname='yck-data-center',stringsAsFactors = F)
# local_defin_yun<-data.frame(user = 'yckdctab',host='47.106.189.86',password= 'YckDCtemp2019',dbname='yck-data-center',stringsAsFactors = F)
# local_defin_yunl<-data.frame(user = "yckdctab",host="172.18.215.178",password= "YckDCtemp2019",dbname="yck-data-center",stringsAsFactors = F)
local_defin_yun_it<-data.frame(user = 'data',host='youcku.com',password= 'ibfIh28',dbname='yck',stringsAsFactors = F)
source(paste0(price_model_loc,"\\function\\fun_model_price.R"),echo=FALSE,encoding="utf-8")
source(paste0(price_model_loc,"\\main\\project_it\\fun_project_it_user.R"),echo=FALSE,encoding="utf-8")